"""followers

Revision ID: 516c30548c42
Revises: 6c9d0a1cfeb9
Create Date: 2021-11-23 16:46:27.031857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516c30548c42'
down_revision = '6c9d0a1cfeb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
